### ISSUE TITLE
请问 bugu-mongo 有支持 MongoDB Java Driver 3.x 的计划吗？

### ISSUE THREAD

**Issue by byrdkm17** [xbwen/bugu-mongo#1]
3.x 将要发布，请问有支持 3.x 的计划吗？

**Comment by xbwen** [comment]
是的，等MongoDB Java Driver 3.0出来后，bugu-mongo将会发布2.0正式版。

**Comment by byrdkm17** [comment]
bugu-mongo 是一个很好的项目，最近一直在学习她的源码，希望能为她的发展提供自己的一份力量

**Comment by xbwen** [comment]
bugu-mongo 2.0.0版本已经发布，它升级到了MongoDB Java Driver 3.0。
感谢你们对bugu-mongo的关注和支持！
