### ISSUE TITLE
出现数组越界问题

### ISSUE THREAD

**Issue by 258513813** [xbwen/bugu-mongo#3]
六月 07, 2016 11:48:47 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [UploadedFile] in context with path [/gzhweb] threw exception
java.lang.ArrayIndexOutOfBoundsException: 3
	at com.bugull.mongo.fs.UploadedFileServlet.processRequest(UploadedFileServlet.java:92)

http://localhost:8080/gzhweb/mgfile/bucket/test_gzh/image1.png

我本地调试的时候，image1.png 是我长传的图片

是这样的，我们的应都是通过 /xxx 的方式来访问的。 我刚刚试过了，如果直接是根路径访问就没有问题，但是如果不是跟路径来访问图片就会出错，这点可以更通用点不？支持非根目录访问？

**Comment by xbwen** [comment]
原因可能是HTTP路径中多了一个斜杠/，比如：http://localhost:8080/gzhweb//mgfile/bucket/test_gzh//image1.png，你可以打印出来看下。

在下一个版本，我把这种多个斜杠的情况考虑进去，避免出错。

**Comment by 258513813** [comment]
不是多一个斜杠， 是项目的根路径就是已/gzhweb  标识一个应用。

**Comment by xbwen** [comment]
好的，谢谢反馈，我针对这种情况debug看下。

**Comment by xbwen** [comment]
2.5.0版本已经解决了该问题。
