### ISSUE TITLE
请问下bugu需要哪个版本的jdk

### ISSUE THREAD

**Issue by 258513813** [xbwen/bugu-mongo#4]
failed; nested exception is java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException]。
我使用ImageUploader的时候出现这个问题，jdk1.7.0_67没有问题，但是jdk1.7.0_95 好像已经移除了com.sun.image.codec.jpeg包

**Comment by xbwen** [comment]
谢谢反馈。在下个版本中，我想办法移除掉对com.sun.image.codec.jpeg的依赖。

**Comment by xbwen** [comment]
2.5.0版本已经解决了该问题。
